language: node_js
node_js:
  - "8"

sudo: required
dist: trusty

before_install:  
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0 
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

branches:
  only:
  - master
  - development
  - stable

install:
  - npm install
  - npm run build

script:
  - npm run test-ci

deploy:
  - provider: script
    script: npm run deploy-gh
    skip_cleanup: true
    on:
      branch: master
